import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const Module = require('node:module');
const constants = require('../shared/constants.js');
const policies = require('../shared/policies.js');
const validators = require('../shared/validators.js');
const errors = require('../shared/errors.js');
const calls = [];

const fakeDb = {
  getDb() {
    return {
      async rpc(name, args) {
        calls.push({ name, args });
        if (name !== 'hg_admin_management') throw new Error(`unexpected RPC ${name}`);
        if (args.p_action === 'invites.create') {
          return {
            inviteId: 'invite-opaque-1', mode: args.p_input.mode, status: 'active', maxUses: args.p_input.maxUses,
            usedCount: 0, reservedCount: 0, expiresAt: '2026-10-10T00:00:00.000Z', version: 1,
            codeHash: 'database-hash-must-not-cross-dto', code: 'database-raw-code-must-not-cross-dto',
          };
        }
        if (args.p_action === 'invites.list') {
          return {
            items: [{
              inviteId: 'invite-opaque-2', mode: 'application', status: 'active', maxUses: 5, usedCount: 1,
              reservedCount: 1, version: 2, code: 'secret-code', codeHash: 'secret-hash', wxOpenIdRef: 'private-openid',
              anonymousMapping: { originalUser: 'private-user' },
            }],
            nextCursor: 'opaque-cursor',
          };
        }
        if (args.p_action === 'members.list') {
          return {
            items: [{
              targetUserId: 'u_member', displayName: '成员', role: 'member', status: 'removed', mutedUntil: null,
              version: 4, managementTermId: 'term-old', wxOpenIdRef: 'secret-openid', codeHash: 'secret-hash',
            }],
            nextCursor: 'member-cursor',
          };
        }
        if (args.p_action === 'audit.list') {
          return {
            items: [{
              id: 'audit-1', actorId: 'u_mod', action: 'invite.revoke', targetType: 'invite', targetId: 'invite-1',
              decision: 'revoked', reason: '不再使用', createdAt: '2026-10-03T00:00:00.000Z',
              codeHash: 'secret-hash', anonymousMapping: { originalUser: 'secret' }, extra: { privatePost: 'secret' },
            }],
            nextCursor: null,
          };
        }
        if (args.p_action === 'recovery.mine') {
          return {
            items: [{
              id: 'recovery-opaque-1', clubId: 'club-paused', clubName: '暂停社团', type: 'recovery',
              status: 'recovery_requested', targetUserId: 'u_target', requesterId: 'u_dev', primaryUserId: 'u_target',
              proposedTeam: [{ targetUserId: 'u_target', displayName: '继任者', role: 'moderator', version: 3, wxOpenIdRef: 'secret' }],
              reason: '负责人无法联系', expiresAt: '2026-10-10T00:00:00.000Z', createdAt: '2026-10-03T00:00:00.000Z', version: 4,
              privateContent: 'must not return', codeHash: 'must not return',
            }],
            nextCursor: null,
          };
        }
        if (args.p_action === 'overview') {
          return {
            club: { id: 'club-a', name: '社团 A', status: 'active', version: 2, rulesVersion: 'v2', wxOpenIdRef: 'secret' },
            pending: { memberships: 2, manualJoin: 1, manualRestore: 1, handovers: 0, privatePosts: 99 },
            activeMembers: 12,
            term: { id: 'term-a', version: 3, primaryUserId: 'u_mod', startAt: '2026-01-01', endAt: '2027-01-01', memberCount: 2, privateContent: 'secret' },
            pendingHandover: null,
            privatePostCount: 999,
          };
        }
        return { ok: true, id: 'opaque-result', status: 'ok', version: 1 };
      },
    };
  },
};

const originalLoad = Module._load;
Module._load = function patchedLoad(request, parent, isMain) {
  if (request.endsWith('/shared/constants')) return constants;
  if (request.endsWith('/shared/policies')) return policies;
  if (request.endsWith('/shared/validators')) return validators;
  if (request.endsWith('/shared/errors')) return errors;
  if (request.endsWith('/shared/db')) return fakeDb;
  return originalLoad.call(this, request, parent, isMain);
};
const management = require('../cloudfunctions/api/domain/adminManagement.js');
Module._load = originalLoad;

const moderator = policies.buildViewer({
  userId: 'u_mod', clubId: 'club-a', role: constants.ROLE.MODERATOR, memberStatus: constants.MEMBER_STATUS.ACTIVE,
});
const target = policies.buildViewer({ userId: 'u_target', clubId: null, role: constants.ROLE.GUEST, memberStatus: constants.MEMBER_STATUS.NONE });
const ctx = (viewer, extra = {}) => ({ viewer, ...extra });

test('new invite secret is generated by the API, hashed before RPC, and returned only once', async () => {
  calls.length = 0;
  const result = await management.createInvite({ mode: 'application', maxUses: 10, ttlSeconds: 3600, reason: '本学期社团招新活动请使用此邀请码' }, ctx(moderator));
  const call = calls[0];
  assert.equal(call.name, 'hg_admin_management');
  assert.equal(call.args.p_action, 'invites.create');
  assert.equal(call.args.p_actor_id, 'u_mod');
  assert.equal(call.args.p_input.code, undefined);
  assert.match(call.args.p_input.codeHash, /^[0-9a-f]{64}$/);
  assert.equal(crypto.createHash('sha256').update(result.code, 'utf8').digest('hex'), call.args.p_input.codeHash);
  assert.match(result.code, /^[A-F0-9]{32}$/);
  assert.equal(result.codeHash, undefined);
});

test('invite list is an allowlisted DTO without code, hash, openid, or anonymous mapping', async () => {
  calls.length = 0;
  const result = await management.listInvites({}, ctx(moderator));
  assert.equal(calls[0].args.p_action, 'invites.list');
  assert.deepEqual(result, {
    items: [{ inviteId: 'invite-opaque-2', mode: 'application', status: 'active', maxUses: 5, usedCount: 1, reservedCount: 1, version: 2 }],
    nextCursor: 'opaque-cursor',
  });
});

test('member pagination forwards filters and returns only the roster DTO', async () => {
  calls.length = 0;
  const result = await management.listMembers({ cursor: 'opaque-member-cursor', limit: 10, status: 'removed' }, ctx(moderator));
  assert.deepEqual(calls[0].args.p_input, { cursor: 'opaque-member-cursor', limit: 10, status: 'removed' });
  assert.deepEqual(result, {
    items: [{
      targetUserId: 'u_member', displayName: '成员', role: 'member', status: 'removed', mutedUntil: null,
      version: 4, managementTermId: 'term-old',
    }],
    nextCursor: 'member-cursor',
  });
});

test('empty member and invite status filters normalize to SQL all status', async () => {
  calls.length = 0;
  await management.listMembers({ status: '' }, ctx(moderator));
  assert.equal(calls[0].args.p_input.status, 'all');
  await management.listInvites({ status: '' }, ctx(moderator));
  assert.equal(calls[1].args.p_input.status, 'all');
  await assert.rejects(management.listMembers({ status: 'rejected' }, ctx(moderator)), /status 取值不合法/);
});

test('invite revoke translates the Web inviteId field to the SQL id field', async () => {
  calls.length = 0;
  await management.revokeInvite({ inviteId: 'invite-opaque-2', expectedVersion: 3, reason: '因活动安排变化需要撤销该邀请码' }, ctx(moderator));
  assert.equal(calls[0].args.p_action, 'invites.revoke');
  assert.equal(calls[0].args.p_input.id, 'invite-opaque-2');
  assert.equal(calls[0].args.p_input.inviteId, undefined);
});

test('team primary accepts the Web target and forwards both SQL versions', async () => {
  calls.length = 0;
  await management.setPrimary({
    targetUserId: 'u_next', expectedVersion: 4, expectedMembershipVersion: 8,
    reason: '初始化本届负责人并记录当前管理状态',
  }, ctx(moderator));
  assert.equal(calls[0].args.p_action, 'team.primary');
  assert.deepEqual(calls[0].args.p_input, {
    targetUserId: 'u_next', expectedVersion: 4, expectedMembershipVersion: 8,
    reason: '初始化本届负责人并记录当前管理状态',
  });
});

test('settings description matches SQL length and recovery status admits stale rows', async () => {
  calls.length = 0;
  await assert.rejects(management.updateSettings({
    expectedVersion: 2, reason: '本次调整说明需要使用至少十个字', description: 'x'.repeat(301),
  }, ctx(moderator)), /最多 300 字/);
  assert.equal(calls.length, 0);

  const developer = policies.buildViewer({ userId: 'u_dev', clubId: null, platformRole: 'developer' });
  await management.listPlatformRecoveries({ status: 'stale' }, ctx(developer, { requestedClubId: 'club-paused' }));
  assert.equal(calls[0].args.p_input.status, 'stale');
});

test('audit DTO excludes arbitrary extra fields, invite hashes, and anonymous mappings', async () => {
  calls.length = 0;
  const result = await management.listAudit({}, ctx(moderator));
  assert.equal(calls[0].args.p_action, 'audit.list');
  assert.deepEqual(result.items[0], {
    id: 'audit-1', actorId: 'u_mod', action: 'invite.revoke', targetType: 'invite', targetId: 'invite-1',
    decision: 'revoked', reason: '不再使用', createdAt: '2026-10-03T00:00:00.000Z',
  });
  assert.equal(JSON.stringify(result).includes('secret'), false);
});

test('target recovery inbox only returns the target-safe team and recovery fields', async () => {
  calls.length = 0;
  const result = await management.listMyRecoveries({}, ctx(target));
  assert.equal(calls[0].args.p_action, 'recovery.mine');
  assert.equal(calls[0].args.p_club_id, null);
  assert.equal(calls[0].args.p_actor_id, 'u_target');
  assert.deepEqual(result.items[0], {
    id: 'recovery-opaque-1', clubId: 'club-paused', clubName: '暂停社团', type: 'recovery',
    status: 'recovery_requested', requesterId: 'u_dev', targetUserId: 'u_target', primaryUserId: 'u_target',
    proposedTeam: [{ targetUserId: 'u_target', displayName: '继任者', role: 'moderator', version: 3 }],
    reason: '负责人无法联系', expiresAt: '2026-10-10T00:00:00.000Z', createdAt: '2026-10-03T00:00:00.000Z', version: 4,
  });
  assert.equal(JSON.stringify(result).includes('must not return'), false);
});

test('overview counts only membership and governance work, never content or private content', async () => {
  calls.length = 0;
  const result = await management.overview({}, ctx(moderator));
  assert.equal(calls[0].args.p_action, 'overview');
  assert.deepEqual(result, {
    club: { id: 'club-a', name: '社团 A', status: 'active', version: 2, rulesVersion: 'v2' },
    pending: { memberships: 2, manualJoin: 1, manualRestore: 1, handovers: 0 },
    activeMembers: 12,
    term: { id: 'term-a', version: 3, primaryUserId: 'u_mod', startAt: '2026-01-01', endAt: '2027-01-01', memberCount: 2 },
    pendingHandover: null,
  });
});

test('recovery acceptance uses the requested club only as database scope and takes actor from session', async () => {
  calls.length = 0;
  await management.acceptMyRecovery({ recoveryId: 'recovery-opaque-1', expectedVersion: 4 }, ctx(target, { requestedClubId: 'club-paused' }));
  assert.equal(calls[0].args.p_actor_id, 'u_target');
  assert.equal(calls[0].args.p_club_id, 'club-paused');
  assert.deepEqual(calls[0].args.p_input, { recoveryId: 'recovery-opaque-1', expectedVersion: 4 });
});

test('platform recovery actions require and forward the selected club scope', async () => {
  const developer = policies.buildViewer({ userId: 'u_dev', clubId: null, platformRole: 'developer' });
  calls.length = 0;
  await management.listPlatformRecoveries({ limit: 10 }, ctx(developer, { requestedClubId: 'club-paused' }));
  assert.equal(calls[0].args.p_action, 'recovery.list');
  assert.equal(calls[0].args.p_club_id, 'club-paused');

  calls.length = 0;
  await management.requestRecovery({
    targetUserId: 'u_target', expectedVersion: 5, reason: '现任负责人失联需要启动平台恢复流程',
  }, ctx(developer, { requestedClubId: 'club-paused' }));
  assert.equal(calls[0].args.p_action, 'recovery.request');
  assert.equal(calls[0].args.p_club_id, 'club-paused');
  assert.deepEqual(calls[0].args.p_input, {
    targetUserId: 'u_target', expectedVersion: 5, reason: '现任负责人失联需要启动平台恢复流程',
  });

  calls.length = 0;
  await management.approveRecovery({
    id: 'recovery-opaque-1', expectedVersion: 6, decision: 'approve', reason: '目标账号已确认且符合二次复核要求',
  }, ctx(developer, { requestedClubId: 'club-paused' }));
  assert.equal(calls[0].args.p_action, 'recovery.approve');
  assert.equal(calls[0].args.p_club_id, 'club-paused');
  assert.deepEqual(calls[0].args.p_input, {
    id: 'recovery-opaque-1', expectedVersion: 6, decision: 'approve', reason: '目标账号已确认且符合二次复核要求',
  });
});

test('management write reasons shorter than SQL minimum fail before RPC', async () => {
  calls.length = 0;
  await assert.rejects(management.createInvite({ mode: 'application', reason: '短理由' }, ctx(moderator)), /处理理由至少需要 10 字/);
  assert.equal(calls.length, 0);
});

test('database recovery and term transition errors map to client-visible business responses', () => {
  for (const marker of ['TARGET_ACCEPTANCE_REQUIRED', 'RECOVERY_EXPIRED', 'RECOVERY_COOLDOWN', 'RECOVERY_SECOND_APPROVAL_REQUIRED']) {
    assert.equal(management.mapManagementError(new Error(marker)).kind, 'conflict');
  }
  assert.equal(management.mapManagementError(new Error('TEAM_INVALID')).kind, 'invalid_input');
  assert.equal(management.mapManagementError(new Error('MANAGEMENT_TERM_NOT_FOUND')).kind, 'not_accessible');
});
