FROM postgres:16-bookworm
COPY cloudbase/migrations/ /opt/blacklight/cloudbase-migrations/
COPY deploy/nas/compat/ /opt/blacklight/compat/
COPY scripts/local-apply-migrations.sh /usr/local/bin/local-apply-migrations
COPY deploy/web/init-db.sh /docker-entrypoint-initdb.d/10-blacklight.sh
RUN chmod -R a+rX /opt/blacklight \
    && chmod 0755 /usr/local/bin/local-apply-migrations /docker-entrypoint-initdb.d/10-blacklight.sh
